### ISSUE TITLE
conditional argument

### ISSUE THREAD

**Issue by chennuo0125** [toeklk/orocos-bayesian-filtering#51]
ColumnVector state = ConditionalArgumentGet(0);
    ColumnVector vel  = ConditionalArgumentGet(1);
i dont konw how to define conditional arguments? are they default ?

**Comment by toeklk** [comment]
I assume this is a question rather than an issue?  Could you please clarify your question?  It looks like you are referring to the BFL tutorial section 3.4.3? Is your question solved by pointing out the that ConditionalArgumentGet() function is implemented in the parent class ConditionalPdf<> ?

Side note: However, I noted that at least the mailing url seems to be (temporarily) down :-(
